[2025-07-22T23:30:29.841+0000] {processor.py:161} INFO - Started process (PID=167) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:30:29.861+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:30:29.873+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:30:29.871+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:30:30.035+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:30:30.018+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:30:30.040+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:30:30.195+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.421 seconds
[2025-07-22T23:31:00.501+0000] {processor.py:161} INFO - Started process (PID=172) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:31:00.502+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:31:00.506+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:31:00.506+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:31:00.565+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:31:00.552+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:31:00.569+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:31:00.655+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.170 seconds
[2025-07-22T23:31:30.889+0000] {processor.py:161} INFO - Started process (PID=177) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:31:30.892+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:31:30.897+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:31:30.895+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:31:30.960+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:31:30.945+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:31:30.963+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:31:31.046+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.189 seconds
[2025-07-22T23:32:01.379+0000] {processor.py:161} INFO - Started process (PID=182) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:32:01.381+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:32:01.387+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:32:01.386+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:32:01.431+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:32:01.424+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:32:01.436+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:32:01.487+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.116 seconds
[2025-07-22T23:32:31.711+0000] {processor.py:161} INFO - Started process (PID=187) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:32:31.714+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:32:31.720+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:32:31.719+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:32:31.780+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:32:31.772+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:32:31.783+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:32:31.851+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.149 seconds
[2025-07-22T23:33:02.133+0000] {processor.py:161} INFO - Started process (PID=192) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:33:02.135+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:33:02.138+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:33:02.137+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:33:02.178+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:33:02.172+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:33:02.181+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:33:02.258+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.130 seconds
[2025-07-22T23:33:32.505+0000] {processor.py:161} INFO - Started process (PID=197) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:33:32.511+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:33:32.514+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:33:32.513+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:33:32.556+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:33:32.547+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:33:32.558+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:33:32.605+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.122 seconds
[2025-07-22T23:34:02.930+0000] {processor.py:161} INFO - Started process (PID=202) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:34:02.932+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:34:02.935+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:34:02.934+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:34:02.988+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:34:02.982+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:34:02.990+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:34:03.023+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.113 seconds
[2025-07-22T23:34:33.266+0000] {processor.py:161} INFO - Started process (PID=207) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:34:33.268+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:34:33.269+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:34:33.269+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:34:33.300+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:34:33.293+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:34:33.302+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:34:33.333+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.072 seconds
[2025-07-22T23:35:03.595+0000] {processor.py:161} INFO - Started process (PID=212) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:35:03.598+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:35:03.600+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:35:03.599+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:35:03.633+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:35:03.627+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:35:03.635+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:35:03.669+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.078 seconds
[2025-07-22T23:35:34.056+0000] {processor.py:161} INFO - Started process (PID=217) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:35:34.057+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:35:34.059+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:35:34.058+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:35:34.089+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:35:34.082+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:35:34.091+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:35:34.118+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.067 seconds
[2025-07-22T23:36:04.363+0000] {processor.py:161} INFO - Started process (PID=222) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:36:04.365+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:36:04.367+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:36:04.367+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:36:04.403+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:36:04.397+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:36:04.406+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:36:04.435+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.079 seconds
[2025-07-22T23:36:34.687+0000] {processor.py:161} INFO - Started process (PID=227) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:36:34.688+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:36:34.689+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:36:34.689+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:36:34.732+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:36:34.725+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:36:34.734+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:36:34.761+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.079 seconds
[2025-07-22T23:37:04.981+0000] {processor.py:161} INFO - Started process (PID=232) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:37:04.982+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:37:04.984+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:37:04.984+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:37:05.024+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:37:05.015+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:37:05.027+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:37:05.054+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.079 seconds
[2025-07-22T23:37:35.393+0000] {processor.py:161} INFO - Started process (PID=237) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:37:35.395+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:37:35.397+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:37:35.396+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:37:35.427+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:37:35.419+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:37:35.431+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:37:35.457+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.069 seconds
[2025-07-22T23:38:05.692+0000] {processor.py:161} INFO - Started process (PID=242) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:38:05.693+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:38:05.695+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:38:05.694+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:38:05.734+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:38:05.726+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:38:05.737+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:38:05.767+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.080 seconds
[2025-07-22T23:38:36.044+0000] {processor.py:161} INFO - Started process (PID=247) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:38:36.045+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:38:36.046+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:38:36.046+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:38:36.072+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:38:36.067+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:38:36.074+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:38:36.098+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.057 seconds
[2025-07-22T23:39:06.342+0000] {processor.py:161} INFO - Started process (PID=252) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:39:06.343+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:39:06.345+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:39:06.344+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:39:06.372+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:39:06.366+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:39:06.374+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:39:06.399+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.061 seconds
[2025-07-22T23:39:36.689+0000] {processor.py:161} INFO - Started process (PID=257) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:39:36.691+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:39:36.693+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:39:36.692+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:39:36.723+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:39:36.716+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:39:36.727+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:39:36.776+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.097 seconds
[2025-07-22T23:40:06.995+0000] {processor.py:161} INFO - Started process (PID=262) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:40:06.997+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:40:06.998+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:40:06.998+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:40:07.032+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:40:07.026+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:40:07.035+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:40:07.073+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.083 seconds
[2025-07-22T23:44:39.477+0000] {processor.py:161} INFO - Started process (PID=167) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:44:39.480+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:44:39.482+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:44:39.481+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:44:39.520+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:44:39.512+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:44:39.523+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:44:39.558+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.087 seconds
[2025-07-22T23:45:09.819+0000] {processor.py:161} INFO - Started process (PID=172) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:45:09.820+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:45:09.822+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:45:09.821+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:45:09.856+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:45:09.848+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:45:09.858+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:45:09.890+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.078 seconds
[2025-07-22T23:45:40.138+0000] {processor.py:161} INFO - Started process (PID=177) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:45:40.139+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:45:40.140+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:45:40.140+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:45:40.173+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:45:40.163+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:45:40.176+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:45:40.211+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.080 seconds
[2025-07-22T23:46:10.454+0000] {processor.py:161} INFO - Started process (PID=182) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:46:10.456+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:46:10.457+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:46:10.457+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:46:10.493+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:46:10.484+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:46:10.496+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:46:10.529+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.082 seconds
[2025-07-22T23:46:40.782+0000] {processor.py:161} INFO - Started process (PID=187) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:46:40.783+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:46:40.785+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:46:40.784+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:46:40.810+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:46:40.804+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:46:40.812+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:46:40.837+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.060 seconds
[2025-07-22T23:47:11.094+0000] {processor.py:161} INFO - Started process (PID=192) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:47:11.096+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:47:11.098+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:47:11.097+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:47:11.129+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:47:11.122+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:47:11.131+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:47:11.158+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.070 seconds
[2025-07-22T23:47:41.412+0000] {processor.py:161} INFO - Started process (PID=197) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:47:41.414+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:47:41.415+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:47:41.415+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:47:41.445+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:47:41.436+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:47:41.448+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:47:41.475+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.069 seconds
[2025-07-22T23:48:11.726+0000] {processor.py:161} INFO - Started process (PID=202) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:48:11.728+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:48:11.730+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:48:11.730+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:48:11.768+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:48:11.760+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:48:11.771+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:48:11.811+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.095 seconds
[2025-07-22T23:48:42.043+0000] {processor.py:161} INFO - Started process (PID=207) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:48:42.044+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:48:42.048+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:48:42.045+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:48:42.076+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:48:42.071+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:48:42.079+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:48:42.107+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.073 seconds
[2025-07-22T23:49:12.361+0000] {processor.py:161} INFO - Started process (PID=212) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:49:12.362+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:49:12.364+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:49:12.363+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:49:12.393+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:49:12.387+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:49:12.394+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:49:12.420+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.063 seconds
[2025-07-22T23:49:42.764+0000] {processor.py:161} INFO - Started process (PID=217) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:49:42.765+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:49:42.767+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:49:42.767+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:49:42.804+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:49:42.797+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:49:42.807+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:49:42.845+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.086 seconds
[2025-07-22T23:50:13.062+0000] {processor.py:161} INFO - Started process (PID=222) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:50:13.064+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:50:13.065+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:50:13.065+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:50:13.096+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:50:13.090+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:50:13.099+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:50:13.124+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.066 seconds
[2025-07-22T23:50:43.416+0000] {processor.py:161} INFO - Started process (PID=227) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:50:43.417+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:50:43.419+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:50:43.418+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:50:43.445+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:50:43.439+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:50:43.447+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:50:43.472+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.060 seconds
[2025-07-22T23:51:13.704+0000] {processor.py:161} INFO - Started process (PID=232) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:51:13.705+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:51:13.707+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:51:13.706+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:51:13.733+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:51:13.726+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:51:13.735+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:51:13.759+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.059 seconds
[2025-07-22T23:51:44.034+0000] {processor.py:161} INFO - Started process (PID=237) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:51:44.036+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:51:44.037+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:51:44.037+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:51:44.065+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:51:44.058+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:51:44.068+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:51:44.098+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.068 seconds
[2025-07-22T23:52:14.323+0000] {processor.py:161} INFO - Started process (PID=242) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:52:14.324+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:52:14.325+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:52:14.325+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:52:14.353+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:52:14.347+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:52:14.355+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:52:14.380+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.061 seconds
[2025-07-22T23:52:44.647+0000] {processor.py:161} INFO - Started process (PID=247) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:52:44.649+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:52:44.651+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:52:44.650+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:52:44.683+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:52:44.675+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:52:44.686+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:52:44.721+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.080 seconds
[2025-07-22T23:53:14.931+0000] {processor.py:161} INFO - Started process (PID=252) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:53:14.932+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:53:14.934+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:53:14.933+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:53:14.957+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:53:14.950+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:53:14.959+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:53:14.995+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.068 seconds
[2025-07-22T23:53:45.248+0000] {processor.py:161} INFO - Started process (PID=257) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:53:45.250+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:53:45.251+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:53:45.251+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:53:45.284+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:53:45.277+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:53:45.287+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:53:45.318+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.073 seconds
[2025-07-22T23:54:15.580+0000] {processor.py:161} INFO - Started process (PID=262) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:54:15.581+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:54:15.583+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:54:15.582+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:54:15.608+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:54:15.602+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:54:15.610+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:54:15.637+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.061 seconds
[2025-07-22T23:54:45.960+0000] {processor.py:161} INFO - Started process (PID=267) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:54:45.961+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:54:45.963+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:54:45.962+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:54:45.994+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:54:45.988+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:54:45.996+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:54:46.030+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.074 seconds
[2025-07-22T23:55:16.257+0000] {processor.py:161} INFO - Started process (PID=272) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:55:16.259+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:55:16.261+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:55:16.260+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:55:16.289+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:55:16.282+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:55:16.291+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:55:16.318+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.064 seconds
[2025-07-22T23:55:46.586+0000] {processor.py:161} INFO - Started process (PID=277) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:55:46.587+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:55:46.590+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:55:46.589+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:55:46.621+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:55:46.615+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:55:46.623+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:55:46.653+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.071 seconds
[2025-07-22T23:56:16.864+0000] {processor.py:161} INFO - Started process (PID=282) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:56:16.865+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:56:16.867+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:56:16.867+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:56:16.911+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:56:16.903+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:56:16.914+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:56:16.961+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.103 seconds
[2025-07-22T23:59:22.715+0000] {processor.py:161} INFO - Started process (PID=168) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:59:22.717+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:59:22.719+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:59:22.719+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:59:22.773+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:59:22.762+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:59:22.776+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:59:22.822+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.111 seconds
[2025-07-22T23:59:53.088+0000] {processor.py:161} INFO - Started process (PID=173) to work on /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:59:53.090+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main_pipeline.py for tasks to queue
[2025-07-22T23:59:53.092+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:59:53.091+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:59:53.130+0000] {logging_mixin.py:188} INFO - [2025-07-22T23:59:53.120+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_pipeline.py", line 4, in <module>
    from transform_all import transform_all
  File "/opt/airflow/dags/transform_all.py", line 1, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-07-22T23:59:53.132+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main_pipeline.py
[2025-07-22T23:59:53.176+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main_pipeline.py took 0.094 seconds
